"""add project workhour

Revision ID: 9f98dad18a3b
Revises: 
Create Date: 2021-02-26 01:27:06.041656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f98dad18a3b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('upl_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['upl_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=True)
    op.create_table('workhours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work', sa.String(length=64), nullable=True),
    sa.Column('hour', sa.Float(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('worker_id', sa.Integer(), nullable=True),
    sa.Column('submit_time', sa.DateTime(), nullable=True),
    sa.Column('state', sa.String(length=64), nullable=True),
    sa.Column('confirm_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workhours_submit_time'), 'workhours', ['submit_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workhours_submit_time'), table_name='workhours')
    op.drop_table('workhours')
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
